export enum DataRequestStatus {
  initiate = -1,
  Request = 0,
  Data_Request_Saved = 1,
  Data_Request_Sent = 2,
  Assign_Data_Request_Saved = 3,
  Assign_Data_Request_Sent = 4,
  Data_Entered = 5,
  Rejected_entered_data = -8,
  QA_Assign = 20,
  QAPass = 21,
  QAFail = 22,
  Verifier_Data_Request = 23,
  Data_Approved = 11,
}
